name: Add new file to repository

on:
  workflow_dispatch:
    inputs:
        file_contents:
            description: "Enter the contents of the file to be created"
            required: true
            type: string

permissions:
  contents: write
  issues: write

jobs:
    create-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Create a new file
              run: |
                touch new_file.md
                echo "${{ inputs.file_contents }}" >> new_file.md
                echo "File 'new_file.md' has been created."
                cat new_file.md

            - name: Commit and push new file
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "Add new file.md"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create an issue using action
              uses: JasonEtco/create-an-issue@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with: 
                filename: ./new_file.md