# Create a workflow that generates a repository health report to MAINTENANCE_LOG.md:
# - Runs the repository health report script located at actions/repo_health_report.sh. This adds a entry to MAINTENANCE_LOG.md
# - Uses peter-evans/create-pull-request@v7 to commit changes and create a PR to the repository
# - Is manually run

name: Repository Health Report

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Health check on repo
        run: ./actions/repo_health_report.sh

      - name: Create new pull request
        uses: peter-evans/create-pull-request@v7
